### ISSUE TITLE
[Forge 1.19.2] Bovine&Buttercup's JEI stuff breaks Bumblezone JEI recipes

### ISSUE THREAD

**Issue by TelepathicGrunt** [MerchantPug/bovines-and-buttercups#17]
Log entries: https://controlc.com/01e14e27

I can export my testing modpack that is full of tons of mods. I saw this in the log where my Bumblezone mod tries to register a Bee Queen trade to JEI that takes flowers to show rewards possible for them. Bovine&Buttercups crashes the flower trade registrations due to a null fuield

```

java.lang.NullPointerException: Cannot invoke "net.merchantpug.bovinesandbuttercups.data.block.FlowerType.equals(Object)" because "flowerType" is null
	at net.merchantpug.bovinesandbuttercups.integration.jei.subtype.CustomFlowerSubtypeInterpreter.apply(CustomFlowerSubtypeInterpreter.java:22) ~[Bovines-And-Buttercups-Forge-1.5.0+1.19.2.jar%23342!/:1.5.0+1.19.2-forge]
	at net.merchantpug.bovinesandbuttercups.integration.jei.subtype.CustomFlowerSubtypeInterpreter.apply(CustomFlowerSubtypeInterpreter.java:11) ~[Bovines-And-Buttercups-Forge-1.5.0+1.19.2.jar%23342!/:1.5.0+1.19.2-forge]
	at mezz.jei.library.ingredients.subtypes.SubtypeManager.lambda$getSubtypeInfo$0(SubtypeManager.java:23) ~[jei-1.19.2-forge-11.6.0.1015.jar%23415!/:11.6.0.1015]

```

**Comment by ChrysanthCow** [comment]
Thanks for the report, I'll look into fixing this.

**Comment by ChrysanthCow** [comment]
I've implemented a null check within the CustomFlowerSubtypeInterpreter and other subtype interpreter classes, I hope that this fixes it.
