### ISSUE TITLE
[Major Crash] Bonemeal Buttercup

### ISSUE THREAD

**Issue by A5ho9999** [MerchantPug/bovines-and-buttercups#20]
Fabric 1.20.1
Version: https://modrinth.com/mod/bovines-and-buttercups/version/1.6.1+1.20-fabric

Using bonemeal causes locking crash, completely unable to load back in that area without players crashing. Believe it's connected to the flowers placed on the ground as removing the cows still resulted in crashing.

```
java.lang.IllegalArgumentException: Cannot get property class_2758{name=flower_amount, clazz=class java.lang.Integer, values=[1, 2, 3, 4]} as it does not exist in Block{bovinesandbuttercups:buttercup}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2356.method_9530(class_2356.java:562)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at net.minecraft.class_3959$class_3960.get(class_3959.java:67)
	at net.minecraft.class_3959.method_17748(class_3959.java:40)
	at net.minecraft.class_1922.method_17743(class_1922.java:80)
	at net.minecraft.class_1922.method_17744(class_1922.java:193)
	at net.minecraft.class_1922.method_17742(class_1922.java:73)
	at net.minecraft.class_1297.method_5745(class_1297.java:1715)
	at net.minecraft.class_757.method_3190(class_757.java:652)
	at net.minecraft.class_757.method_3188(class_757.java:1067)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

```
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2356.method_9530(class_2356.java:562)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at net.minecraft.class_3959$class_3960.get(class_3959.java:67)
	at net.minecraft.class_3959.method_17748(class_3959.java:40)
	at net.minecraft.class_1922.method_17743(class_1922.java:80)
	at net.minecraft.class_1922.method_17744(class_1922.java:193)
	at net.minecraft.class_1922.method_17742(class_1922.java:73)
	at net.minecraft.class_1297.method_5745(class_1297.java:1715)
	at net.minecraft.class_757.method_3190(class_757.java:652)
	at net.minecraft.class_757.method_3188(class_757.java:1067)

-- Affected level --
Details:
	All players: 1 total; [class_746['A5ho9999'/377426, l='ClientLevel', x=-356.89, y=76.03, z=2630.40]]
	Chunk stats: 4096, 52
	Level dimension: minecraft:overworld
	Level spawn location: World: (-92,110,120), Section: (at 4,14,8 in -6,6,7; chunk contains blocks -96,-64,112 to -81,319,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 21152295 game time, 19610399 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by ChrysanthCow** [comment]
mm, I mustn't have accounted for the new cherry grove flowers and what they added.

I'll look into a fix after I nap.

**Comment by ChrysanthCow** [comment]
@A5ho9999 Are you using a mod that increases the amount that flower nlocks can stack into? Because if so, there's an incompatibility between the two.

**Comment by A5ho9999** [comment]
Yes, we are using both 
https://modrinth.com/mod/bushier-flowers
https://modrinth.com/mod/stackable-flowers

**Comment by ChrysanthCow** [comment]
Yeah, that's an incompatibility then.
I'll see if I can integrate these two mods to support Bovines for next update, thanks.

**Comment by A5ho9999** [comment]
That would be great, thank you!

**Comment by ChrysanthCow** [comment]
After taking a closer look, the issue lies in Stackable Flowers rather than Bushier Flowers.

Bushier Flowers kinda does its own thing and doesn't seem to regard modded flowers, so I'm unsure if I want to include an integration there, but I will anyways.

**Comment by ChrysanthCow** [comment]
Okay, so both mods are kinda written in a way that are not suitable for compat.

I'd only be able to manage fixing the crash with Stackable Flowers myself, I might bring issues up to the two related repos about modded flower compat.
